### ISSUE TITLE
The block of training ElucidatedDiffusion model

### ISSUE THREAD

**Issue by Liuxueyi** [Jaewoopudding/GTA#1]
When run the train_diffuser.py script by the default parameters, the training procedure is blocked at the 443 line `denoised = self.preconditioned_network_forward(noised_inputs, sigmas, cond=cond)` in elucidated_diffusion.py.

**Comment by Jaewoopudding** [comment]
Hello Liuxueyi, could you please provide the detailed error message you got?

**Comment by Liuxueyi** [comment]
There is no error message, just bolcked. And the terminal output message is as following, 
`pybullet build time: May 20 2022 19:44:17
/home/lxy/anaconda3/envs/daug/lib/python3.8/site-packages/scipy/__init__.py:146: UserWarning: A NumPy version >=1.16.5 and <1.23.0 is required for this version of SciPy (detected version 1.24.4
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"
Warning: Flow failed to import. Set the environment variable D4RL_SUPPRESS_IMPORT_ERROR=1 to suppress this message.
No module named 'flow'
/home/lxy/anaconda3/envs/daug/lib/python3.8/site-packages/glfw/__init__.py:916: GLFWError: (65544) b'X11: The DISPLAY environment variable is missing'
  warnings.warn(message, GLFWError)
Warning: CARLA failed to import. Set the environment variable D4RL_SUPPRESS_IMPORT_ERROR=1 to suppress this message.
No module named 'carla'
/home/lxy/anaconda3/envs/daug/lib/python3.8/site-packages/gym/spaces/box.py:84: UserWarning: [33mWARN: Box bound precision lowered by casting to float32[0m
  logger.warn(f"Box bound precision lowered by casting to {self.dtype}")
Means: tensor([-0.0685,  0.0164, -0.1836, -0.2762, -0.3411, -0.0934, -0.2132, -0.0877,
         5.1732, -0.0428, -0.0361,  0.1405,  0.0605,  0.0955,  0.0674,  0.0056,
         0.0134, -0.3227, -0.4105, -0.7346, -0.1233, -0.4680, -0.1580,  4.7703])
Stds: tensor([ 0.0748,  0.3025,  0.3022,  0.3443,  0.1763,  0.5073,  0.2568,  0.3296,
         1.2578,  0.7602,  1.9806,  6.5683,  7.4678,  4.4745, 10.5697,  5.6732,
         7.5004,  0.8053,  0.6702,  0.5493,  0.6834,  0.6408,  0.7196,  1.2102])
terminal penalty :  100
load with Diffusion Trajectory Dataset

  0%|          | 0/1000 [00:00<?, ?it/s]
  2%|▏         | 21/1000 [00:00<00:04, 203.20it/s]
  4%|▍         | 42/1000 [00:00<00:04, 205.38it/s]
  6%|▋         | 63/1000 [00:00<00:04, 206.11it/s]
  8%|▊         | 84/1000 [00:00<00:04, 206.18it/s]
 10%|█         | 105/1000 [00:00<00:04, 206.43it/s]
 13%|█▎        | 126/1000 [00:00<00:04, 205.17it/s]
 15%|█▍        | 147/1000 [00:00<00:04, 204.49it/s]
 17%|█▋        | 168/1000 [00:00<00:04, 204.02it/s]
 19%|█▉        | 189/1000 [00:00<00:03, 203.86it/s]
 21%|██        | 210/1000 [00:01<00:03, 204.18it/s]
 23%|██▎       | 231/1000 [00:01<00:03, 203.75it/s]
 25%|██▌       | 252/1000 [00:01<00:03, 203.89it/s]
 27%|██▋       | 273/1000 [00:01<00:03, 204.39it/s]
 29%|██▉       | 294/1000 [00:01<00:03, 204.64it/s]
 32%|███▏      | 315/1000 [00:01<00:03, 205.19it/s]
 34%|███▎      | 336/1000 [00:01<00:03, 204.94it/s]
 36%|███▌      | 357/1000 [00:01<00:03, 205.11it/s]
 38%|███▊      | 378/1000 [00:01<00:03, 203.17it/s]
 40%|███▉      | 399/1000 [00:01<00:02, 204.10it/s]
 42%|████▏     | 420/1000 [00:02<00:02, 203.93it/s]
 44%|████▍     | 441/1000 [00:02<00:02, 203.99it/s]
 46%|████▌     | 462/1000 [00:02<00:02, 204.45it/s]
 48%|████▊     | 483/1000 [00:02<00:02, 205.16it/s]
 50%|█████     | 504/1000 [00:02<00:02, 205.43it/s]
 52%|█████▎    | 525/1000 [00:02<00:02, 206.17it/s]
 55%|█████▍    | 546/1000 [00:02<00:02, 206.66it/s]
 57%|█████▋    | 567/1000 [00:02<00:02, 207.05it/s]
 59%|█████▉    | 588/1000 [00:02<00:02, 203.96it/s]
 61%|██████    | 609/1000 [00:02<00:01, 205.30it/s]
 63%|██████▎   | 630/1000 [00:03<00:01, 205.60it/s]
 65%|██████▌   | 651/1000 [00:03<00:01, 206.10it/s]
 67%|██████▋   | 672/1000 [00:03<00:01, 206.42it/s]
 69%|██████▉   | 693/1000 [00:03<00:01, 206.61it/s]
 71%|███████▏  | 714/1000 [00:03<00:01, 206.97it/s]
 74%|███████▎  | 735/1000 [00:03<00:01, 206.49it/s]
 76%|███████▌  | 756/1000 [00:03<00:01, 206.21it/s]
 78%|███████▊  | 777/1000 [00:03<00:01, 206.57it/s]
 80%|███████▉  | 798/1000 [00:03<00:00, 206.61it/s]
 82%|████████▏ | 819/1000 [00:03<00:00, 206.22it/s]
 84%|████████▍ | 840/1000 [00:04<00:00, 206.34it/s]
 86%|████████▌ | 861/1000 [00:04<00:00, 206.31it/s]
 88%|████████▊ | 882/1000 [00:04<00:00, 206.10it/s]
 90%|█████████ | 903/1000 [00:04<00:00, 206.32it/s]
 92%|█████████▏| 924/1000 [00:04<00:00, 206.39it/s]
 94%|█████████▍| 945/1000 [00:04<00:00, 206.42it/s]
 97%|█████████▋| 966/1000 [00:04<00:00, 206.54it/s]
 99%|█████████▊| 987/1000 [00:04<00:00, 206.65it/s]
100%|██████████| 1000/1000 [00:04<00:00, 205.52it/s]
wandb: Currently logged in as: liuxy_ia (liuxy_ucas). Use `wandb login --relogin` to force relogin
wandb: wandb version 0.17.0 is available!  To upgrade, please run:
wandb:  $ pip install wandb --upgrade
wandb: Tracking run with wandb version 0.15.4
wandb: Run data is saved locally in /home/lxy/mamba_dreamer/GTA/wandb/run-20240601_093257-oufu8p1u
wandb: Run `wandb offline` to turn off syncing.
wandb: Syncing run 09:32
wandb: ⭐️ View project at https://wandb.ai/liuxy_ucas/gta
wandb: 🚀 View run at https://wandb.ai/liuxy_ucas/gta/runs/oufu8p1u
The Number of Trajectories:  970000
Number of trainable parameters: 29628949.
Using batch size: 256
using CosineAnnealingWarmRestarts scheduler

  0%|          | 0/1000000 [00:00<?, ?it/s]`

**Comment by Jaewoopudding** [comment]
Thank you for sharing additional details. 
I've reviewed the versions of numpy and scipy specified in the requirements.txt file, which are 1.21.6 and 1.7.3 respectively.
Based on your error message, it seems there are discrepancies in the versions of numpy and scipy you have installed, suggesting possible version mismatches in the core packages. Could you please set up a new virtual environment using Python 3.8.19 and install the packages by executing pip install -r requirements.txt?

**Comment by Liuxueyi** [comment]
Here is an incompatible error when using the version specified:
`numpy.ndarray size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject
  File "/home/lxy/mamba_dreamer/GTA/src/diffusion/utils.py", line 4, in <module>
    import d4rl
  File "/home/lxy/mamba_dreamer/GTA/src/diffusion/train_diffuser.py", line 34, in <module>
    from src.diffusion.utils import split_diffusion_trajectory, construct_diffusion_model
ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject`
